### PR TITLE
lol 201 guilds go brr

### PR DESCRIPTION
**Pull request by Commandtechno**
in the rare case that somebody breaks discord more than we initially expected they would break discord this should work but im not sure i havent tested it i should probably do that

### CODE REVIEW

**Comment by Commandtechno** [comment]
fuck i had vscode auto formatter on

**Comment by Commandtechno** [comment]
there we go i fixed it

**Comment by Commandtechno** [comment]
how do i test it to make sure it doesnt shit itself lol

**Comment by ItsRauf** [comment]
repo is moved to https://github.com/ItsRauf/guildcount and has implemented this fix

**Pull request closed without merging**
